package net.officefloor.hq.app;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * A client the user tracks: a name and an email. Mapped to the {@code client} table created by
 * {@code V1__clients.sql}. IDENTITY id so the DB assigns it on insert (seed inserts explicit ids
 * via JdbcTemplate; GENERATED BY DEFAULT allows both).
 */
@Entity
@Table(name = "client")
public class Client {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;

    private String email;

    /** Archived clients are kept but hidden from the default list and search (V19__client_archived.sql). */
    @Column(nullable = false)
    private boolean archived;

    /**
     * The currency this client is billed in (an ISO code, {@code USD} or {@code EUR}). Their money is
     * shown in this currency everywhere it appears — invoice rows, the project total, the statement,
     * the dashboard totals and the top-clients list — and currencies are never added together. Stored
     * by {@code V33__client_currency.sql}, defaulting to USD for clients created before it existed.
     */
    @Column(nullable = false)
    private String currency;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public boolean isArchived() {
        return archived;
    }

    public void setArchived(boolean archived) {
        this.archived = archived;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }
}
