package net.officefloor.hq.app;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import java.math.BigDecimal;
import java.math.RoundingMode;

/**
 * An invoice raised against a project: the id of the {@link Project} it belongs to and a money
 * amount. Mapped to the {@code invoice} table created by {@code V4__invoices.sql}. IDENTITY id so
 * the DB assigns it on insert (seed inserts explicit ids via JdbcTemplate; GENERATED BY DEFAULT
 * allows both).
 */
@Entity
@Table(name = "invoice")
public class Invoice {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "project_id")
    private Long projectId;

    private BigDecimal amount;

    /**
     * Lifecycle status: DRAFT by default, SENT once sent, PAID once paid (see V5__invoice_status.sql
     * and V11__invoice_draft_default.sql).
     */
    private String status;

    /** The day the invoice went out, an ISO date literal (see V9__invoice_dates.sql). */
    @Column(name = "issued_date")
    private String issuedDate;

    /** The day the invoice is due, an ISO date literal (see V9__invoice_dates.sql). */
    @Column(name = "due_date")
    private String dueDate;

    /**
     * A percentage discount taken off this invoice's subtotal (the sum of its line items), 0 when
     * none. The discount amount and the final total (subtotal minus the discount) are derived from
     * this percentage — see {@link InvoiceSummaryGet}. Stored by {@code V28__invoice_discount_pct.sql}.
     */
    @Column(name = "discount_pct")
    private BigDecimal discountPct;

    /**
     * A sales-tax percentage added on top of this invoice AFTER the discount, 0 when none. The tax
     * amount and the final taxed total ((subtotal minus discount) times (1 plus this rate)) are
     * derived from this percentage — see {@link InvoiceSummaryGet}. Stored by
     * {@code V29__invoice_tax_pct.sql}.
     */
    @Column(name = "tax_pct")
    private BigDecimal taxPct;

    /**
     * How much is still owed on this invoice: its {@link #amount} minus every payment recorded
     * against it. Derived, not stored — {@code @Transient} keeps it out of the {@code invoice}
     * table; {@link InvoicesGet} fills it from the payments before sending the list so the project
     * invoices view can show the amount still due after payments.
     */
    @Transient
    private BigDecimal amountDue;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getProjectId() {
        return projectId;
    }

    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getIssuedDate() {
        return issuedDate;
    }

    public void setIssuedDate(String issuedDate) {
        this.issuedDate = issuedDate;
    }

    public String getDueDate() {
        return dueDate;
    }

    public void setDueDate(String dueDate) {
        this.dueDate = dueDate;
    }

    public BigDecimal getAmountDue() {
        return amountDue;
    }

    public void setAmountDue(BigDecimal amountDue) {
        this.amountDue = amountDue;
    }

    public BigDecimal getDiscountPct() {
        return discountPct;
    }

    public void setDiscountPct(BigDecimal discountPct) {
        this.discountPct = discountPct;
    }

    public BigDecimal getTaxPct() {
        return taxPct;
    }

    public void setTaxPct(BigDecimal taxPct) {
        this.taxPct = taxPct;
    }

    /**
     * What is actually owed on this invoice before payments: its {@link #amount} (the subtotal)
     * minus the discount its {@link #discountPct} takes off, then the sales tax its {@link #taxPct}
     * adds on top of that discounted figure — the same derivation {@link InvoiceSummaryGet} makes for
     * the invoice-detail final amount ((subtotal minus discount) times (1 plus the tax rate)), each
     * step rounded to cents HALF_UP. Derived, not stored (Hibernate uses field access, so this getter
     * is not a mapped property), so every place that shows the invoice amount — the invoice, the
     * statement and the dashboard — applies one discount and one tax.
     */
    public BigDecimal getDiscountedAmount() {
        BigDecimal amt = amount == null ? BigDecimal.ZERO : amount;
        BigDecimal pct = discountPct == null ? BigDecimal.ZERO : discountPct;
        BigDecimal discount = amt.multiply(pct)
                .divide(BigDecimal.valueOf(100), 2, RoundingMode.HALF_UP);
        BigDecimal discounted = amt.subtract(discount);
        BigDecimal taxRate = taxPct == null ? BigDecimal.ZERO : taxPct;
        BigDecimal tax = discounted.multiply(taxRate)
                .divide(BigDecimal.valueOf(100), 2, RoundingMode.HALF_UP);
        return discounted.add(tax);
    }
}
