package net.officefloor.hq.app;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.math.BigDecimal;

/**
 * An invoice raised against a project: the id of the {@link Project} it belongs to and a money
 * amount. Mapped to the {@code invoice} table created by {@code V4__invoices.sql}. IDENTITY id so
 * the DB assigns it on insert (seed inserts explicit ids via JdbcTemplate; GENERATED BY DEFAULT
 * allows both).
 */
@Entity
@Table(name = "invoice")
public class Invoice {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "project_id")
    private Long projectId;

    private BigDecimal amount;

    /** Payment status: UNPAID by default, PAID once marked paid (see V5__invoice_status.sql). */
    private String status;

    /** The day the invoice went out, an ISO date literal (see V9__invoice_dates.sql). */
    @Column(name = "issued_date")
    private String issuedDate;

    /** The day the invoice is due, an ISO date literal (see V9__invoice_dates.sql). */
    @Column(name = "due_date")
    private String dueDate;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getProjectId() {
        return projectId;
    }

    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getIssuedDate() {
        return issuedDate;
    }

    public void setIssuedDate(String issuedDate) {
        this.issuedDate = issuedDate;
    }

    public String getDueDate() {
        return dueDate;
    }

    public void setDueDate(String dueDate) {
        this.dueDate = dueDate;
    }
}
