package net.officefloor.hq.app;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * A free-text note the user keeps against a target (a project, for now). Polymorphic: it names its
 * target by {@code targetType}/{@code targetId} rather than a hard FK. {@code text} is the note body
 * and {@code at} is the ISO-8601 UTC instant it was written (stored as text so it sorts lexically =
 * chronologically). Mapped to the {@code note} table created by {@code V18__notes.sql}. IDENTITY id
 * so the DB assigns it on insert (seed inserts explicit ids via JdbcTemplate; GENERATED BY DEFAULT
 * allows both).
 */
@Entity
@Table(name = "note")
public class Note {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "target_type")
    private String targetType;

    @Column(name = "target_id")
    private Long targetId;

    @Column(name = "note_text")
    private String text;

    @Column(name = "created_at")
    private String at;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTargetType() {
        return targetType;
    }

    public void setTargetType(String targetType) {
        this.targetType = targetType;
    }

    public Long getTargetId() {
        return targetId;
    }

    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getAt() {
        return at;
    }

    public void setAt(String at) {
        this.at = at;
    }
}
