package net.officefloor.hq.app;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import java.math.BigDecimal;

/**
 * One payment a client has made against an {@link Invoice}: how much ({@code amount}) and on what day
 * ({@code date}, an ISO {@code YYYY-MM-DD} string stored as text so it sorts lexically =
 * chronologically), plus the id of the invoice it belongs to. Mapped to the {@code payment} table
 * created by {@code V20__payments.sql}. IDENTITY id so the DB assigns it on insert (seed inserts
 * explicit ids via JdbcTemplate; GENERATED BY DEFAULT allows both).
 */
@Entity
@Table(name = "payment")
public class Payment {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "invoice_id")
    private Long invoiceId;

    private BigDecimal amount;

    @Column(name = "paid_date")
    private String date;

    /**
     * When this payment is one share of a lump payment split across several invoices, the reference
     * of that lump payment (the same value on every allocation of the one payment); null for a
     * standalone single-invoice payment. Set by {@link PaymentsAllocatePost}; stored by
     * {@code V32__payment_batch_ref.sql}.
     */
    @Column(name = "batch_ref")
    private String batchRef;

    /**
     * The currency this payment's amount is shown in — the billing currency of the client the
     * payment's invoice belongs to (an ISO code, {@code USD} or {@code EUR}). Derived, not stored
     * ({@code @Transient} keeps it out of the {@code payment} table); {@link PaymentsGet} fills it by
     * joining the payment's invoice back to its project's client, so the invoice-detail payments read
     * in the same currency as the invoice.
     */
    @Transient
    private String currency;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getInvoiceId() {
        return invoiceId;
    }

    public void setInvoiceId(Long invoiceId) {
        this.invoiceId = invoiceId;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getBatchRef() {
        return batchRef;
    }

    public void setBatchRef(String batchRef) {
        this.batchRef = batchRef;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }
}
