package net.officefloor.hq.app;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * A label a user can put on projects to group them: just a name. Mapped to the {@code tag} table
 * created by {@code V17__project_tags.sql}. A tag is created once and reused across projects via the
 * {@link ProjectTag} join. IDENTITY id so the DB assigns it on insert (seed inserts explicit ids via
 * JdbcTemplate; GENERATED BY DEFAULT allows both).
 */
@Entity
@Table(name = "tag")
public class Tag {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
