package net.officefloor.hq.app;

import java.util.List;
import java.util.Map;
import java.util.function.Consumer;
import org.springframework.context.annotation.Profile;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * Per-spec data setup for the harness (DESIGN.md §9). Profile-guarded so it exists ONLY under the
 * harness launch (bin/start sets spring.profiles.active=harness) — never in a real deploy. This is
 * APP CODE and EVOLVES with the schema (NOT pinned); a change that breaks a prior spec's seed is a
 * seed-path regression. Tests call these to ARRANGE data; they ASSERT only through the UI.
 */
@Profile("harness")
@RestController
@RequestMapping("/__test__")
public class TestSupportController {

    private final Audit audit;
    private final JdbcTemplate jdbc;

    public TestSupportController(Audit audit, JdbcTemplate jdbc) {
        this.audit = audit;
        this.jdbc = jdbc;
    }

    /**
     * Domain tables in FK-dependency order (child before parent). Referential integrity is dropped
     * around the truncates so the order is not load-bearing, but keeping it sensible documents the
     * shape. A new table joins the reset by being added to this list — no new statement to write.
     */
    private static final List<String> DOMAIN_TABLES =
            List.of("project_tag", "tag", "line_item", "invoice", "task", "contact", "project",
                    "client");

    /** Truncate all domain tables and clear the audit file so each spec starts clean. */
    @PostMapping("/reset")
    public void reset() {
        audit.clear();
        // Drop referential integrity around the truncates: RESTART IDENTITY on each, then restore
        // it. That makes the order above cosmetic and clears every FK-referenced table cleanly.
        jdbc.execute("SET REFERENTIAL_INTEGRITY FALSE");
        for (String table : DOMAIN_TABLES) {
            jdbc.execute("TRUNCATE TABLE " + table + " RESTART IDENTITY");
        }
        jdbc.execute("SET REFERENTIAL_INTEGRITY TRUE");
    }

    /**
     * Insert the fixture a spec needs; the payload shape evolves with the schema. Each table is one
     * {@link #seedRows} call: name the fixture key, then map a row to an INSERT. A new table is one
     * more call here — the null-check and per-row loop are shared, not repeated.
     */
    @PostMapping("/seed")
    public void seed(@RequestBody Map<String, Object> fixture) {
        seedRows(fixture, "clients", c -> jdbc.update(
                "INSERT INTO client (id, name, email) VALUES (?, ?, ?)",
                asLong(c, "id"), c.get("name"), c.get("email")));

        seedRows(fixture, "projects", p -> jdbc.update(
                "INSERT INTO project (id, name, client_id) VALUES (?, ?, ?)",
                asLong(p, "id"), p.get("name"), asLong(p, "clientId")));

        seedRows(fixture, "tasks", t -> jdbc.update(
                "INSERT INTO task (id, project_id, title, done) VALUES (?, ?, ?, ?)",
                asLong(t, "id"), asLong(t, "projectId"), t.get("title"),
                Boolean.TRUE.equals(t.get("done"))));

        seedRows(fixture, "tags", t -> jdbc.update(
                "INSERT INTO tag (id, name) VALUES (?, ?)",
                asLong(t, "id"), t.get("name")));

        // A project_tag row is a (project, tag) pairing with no id of its own in the fixture — let the
        // IDENTITY column assign one (GENERATED BY DEFAULT allows the omission).
        seedRows(fixture, "projectTags", pt -> jdbc.update(
                "INSERT INTO project_tag (project_id, tag_id) VALUES (?, ?)",
                asLong(pt, "projectId"), asLong(pt, "tagId")));

        seedRows(fixture, "contacts", c -> jdbc.update(
                "INSERT INTO contact (id, client_id, name, email, role) VALUES (?, ?, ?, ?, ?)",
                asLong(c, "id"), asLong(c, "clientId"),
                c.get("name"), c.get("email"), c.get("role")));

        // An invoice is now itemised: its amount is the sum of qty * unit price across its lines
        // (nested under the invoice in the fixture). The stored amount is the derived total — the
        // fixture may still supply an explicit "amount" for an invoice with no lines, otherwise it
        // is computed here so the invoice list reads the same total the lines add up to.
        seedRows(fixture, "invoices", i -> {
            List<Map<String, Object>> lines = asRows(i.get("lineItems"));
            double computed = 0;
            for (Map<String, Object> li : lines) {
                computed += ((Number) li.get("qty")).doubleValue()
                        * ((Number) li.get("unitPrice")).doubleValue();
            }
            Object explicit = i.get("amount");
            double amount = explicit == null ? computed : ((Number) explicit).doubleValue();
            jdbc.update(
                    "INSERT INTO invoice (id, project_id, amount, status, issued_date, due_date) "
                            + "VALUES (?, ?, ?, ?, ?, ?)",
                    asLong(i, "id"), asLong(i, "projectId"), amount,
                    i.get("status") == null ? "UNPAID" : i.get("status"),
                    i.get("issuedDate"), i.get("dueDate"));
            for (Map<String, Object> li : lines) {
                jdbc.update(
                        "INSERT INTO line_item (id, invoice_id, description, qty, unit_price) "
                                + "VALUES (?, ?, ?, ?, ?)",
                        asLong(li, "id"), asLong(i, "id"), li.get("description"),
                        ((Number) li.get("qty")).intValue(),
                        ((Number) li.get("unitPrice")).doubleValue());
            }
        });
    }

    /** A nested optional list of rows (e.g. an invoice's line items), or empty when the key is absent. */
    @SuppressWarnings("unchecked")
    private static List<Map<String, Object>> asRows(Object value) {
        return value == null ? List.of() : (List<Map<String, Object>>) value;
    }

    /**
     * Run {@code insert} for each row under {@code key}, or do nothing if the fixture omits that key.
     * This is the shared "optional list of rows" shape every table seed follows.
     */
    @SuppressWarnings("unchecked")
    private void seedRows(Map<String, Object> fixture, String key,
            Consumer<Map<String, Object>> insert) {
        List<Map<String, Object>> rows = (List<Map<String, Object>>) fixture.get(key);
        if (rows == null) {
            return;
        }
        for (Map<String, Object> row : rows) {
            insert.accept(row);
        }
    }

    /** Read a JSON number field as a {@code long} (JSON integers arrive as {@link Number}). */
    private static long asLong(Map<String, Object> row, String key) {
        return ((Number) row.get(key)).longValue();
    }
}
