package net.officefloor.hq.app;

import java.util.List;
import java.util.Map;
import java.util.function.Function;
import org.springframework.context.annotation.Profile;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * Per-spec data setup for the harness (DESIGN.md §9). Profile-guarded so it exists ONLY under the
 * harness launch (bin/start sets spring.profiles.active=harness) — never in a real deploy. This is
 * APP CODE and EVOLVES with the schema (NOT pinned); a change that breaks a prior spec's seed is a
 * seed-path regression. Tests call these to ARRANGE data; they ASSERT only through the UI.
 */
@Profile("harness")
@RestController
@RequestMapping("/__test__")
public class TestSupportController {

    private final Audit audit;
    private final JdbcTemplate jdbc;

    public TestSupportController(Audit audit, JdbcTemplate jdbc) {
        this.audit = audit;
        this.jdbc = jdbc;
    }

    /**
     * Every domain table, child-before-parent. Referential integrity is dropped around the
     * TRUNCATE so the order is only for readability of the FK chain (invoices -> projects ->
     * clients). Add a new table here (and a matching {@code seedTable} call) to extend the harness.
     */
    private static final List<String> TABLES =
            List.of("invoice_payments", "invoice_line_items", "invoices", "notes", "tasks",
                    "contacts", "project_tags", "projects", "tags", "clients", "app_settings");

    /** Truncate all domain tables and clear the audit file so each spec starts clean. */
    @PostMapping("/reset")
    public void reset() {
        audit.clear();
        jdbc.execute("SET REFERENTIAL_INTEGRITY FALSE");
        for (String table : TABLES) {
            jdbc.execute("TRUNCATE TABLE " + table + " RESTART IDENTITY");
        }
        jdbc.execute("SET REFERENTIAL_INTEGRITY TRUE");
    }

    /** Insert the fixture a spec needs; the payload shape evolves with the schema. */
    @PostMapping("/seed")
    public void seed(@RequestBody Map<String, Object> fixture) {
        seedTable(fixture, "clients",
                "INSERT INTO clients (id, name, email, archived) VALUES (?, ?, ?, ?)",
                c -> new Object[] {id(c, "id"), c.get("name"), c.get("email"),
                        Boolean.TRUE.equals(c.get("archived"))});
        seedTable(fixture, "projects",
                "INSERT INTO projects (id, name, client_id, status, archived, budget, code)"
                        + " VALUES (?, ?, ?, ?, ?, ?, ?)",
                p -> new Object[] {id(p, "id"), p.get("name"), id(p, "clientId"),
                        p.getOrDefault("status", "ACTIVE"), Boolean.TRUE.equals(p.get("archived")),
                        p.get("budget") == null ? null : ((Number) p.get("budget")).doubleValue(),
                        p.get("code")});
        seedTable(fixture, "contacts",
                "INSERT INTO contacts (id, name, email, role, client_id, is_primary)"
                        + " VALUES (?, ?, ?, ?, ?, ?)",
                c -> new Object[] {id(c, "id"), c.get("name"), c.get("email"), c.get("role"),
                        id(c, "clientId"), Boolean.TRUE.equals(c.get("primary"))});
        seedTable(fixture, "tasks", "INSERT INTO tasks (id, title, done, project_id) VALUES (?, ?, ?, ?)",
                t -> new Object[] {id(t, "id"), t.get("title"), Boolean.TRUE.equals(t.get("done")),
                        id(t, "projectId")});
        seedTable(fixture, "notes",
                "INSERT INTO notes (id, target_type, target_id, note_text, noted_at) VALUES (?, ?, ?, ?, ?)",
                n -> new Object[] {id(n, "id"), n.get("targetType"), id(n, "targetId"), n.get("text"),
                        n.get("at")});
        // Notes are pre-seeded AND created through the API in the same spec, so the identity has to
        // continue past the seeded ids (a raw insert of an explicit id does not advance H2's
        // GENERATED BY DEFAULT sequence — the next app insert would otherwise collide on id=1).
        restartIdentity("notes");
        seedTable(fixture, "tags", "INSERT INTO tags (id, name) VALUES (?, ?)",
                t -> new Object[] {id(t, "id"), t.get("name")});
        seedTable(fixture, "projectTags",
                "INSERT INTO project_tags (project_id, tag_id) VALUES (?, ?)",
                pt -> new Object[] {id(pt, "projectId"), id(pt, "tagId")});
        seedInvoices(fixture);
        seedTable(fixture, "payments",
                "INSERT INTO invoice_payments (id, invoice_id, amount, paid_on) VALUES (?, ?, ?, ?)",
                p -> new Object[] {id(p, "id"), id(p, "invoiceId"),
                        ((Number) p.get("amount")).doubleValue(), p.get("date")});
        // Payments are pre-seeded AND created through the API in the same spec, so the identity has
        // to continue past the seeded ids (a raw insert of an explicit id does not advance H2's
        // GENERATED BY DEFAULT sequence — the next app insert would otherwise collide on id=1).
        restartIdentity("invoice_payments");
        // The dashboard's reference date for "overdue", a top-level scalar (not a table of rows) so
        // the count is deterministic. Absent = the dashboard falls back to today.
        Object asOf = fixture.get("asOf");
        if (asOf != null) {
            jdbc.update("INSERT INTO app_settings (setting_key, setting_value) VALUES ('asOf', ?)",
                    asOf.toString());
        }
    }

    /**
     * Seed invoices and, nested under each, its line items. An invoice's amount is the sum of its
     * lines' qty * unitPrice, so when a fixture lists {@code lineItems} the amount is derived from
     * them (the user no longer types one figure); a fixture may still give an explicit
     * {@code amount} instead (an invoice with no lines). One method rather than a plain seedTable
     * call because the line items live inside each invoice, keyed by the invoice's own id.
     */
    @SuppressWarnings("unchecked")
    private void seedInvoices(Map<String, Object> fixture) {
        List<Map<String, Object>> invoices = (List<Map<String, Object>>) fixture.get("invoices");
        if (invoices == null) {
            return;
        }
        for (Map<String, Object> invoice : invoices) {
            seedInvoice(invoice);
        }
    }

    /** Insert one invoice row and, under it, its line items. */
    @SuppressWarnings("unchecked")
    private void seedInvoice(Map<String, Object> invoice) {
        long invoiceId = id(invoice, "id");
        List<Map<String, Object>> lineItems = (List<Map<String, Object>>) invoice.get("lineItems");
        jdbc.update("INSERT INTO invoices"
                + " (id, project_id, amount, status, issued_date, due_date, discount_pct, tax_pct)"
                + " VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
                invoiceId, id(invoice, "projectId"), invoiceAmount(invoice, lineItems),
                invoice.getOrDefault("status", "DRAFT"), invoice.get("issuedDate"),
                invoice.get("dueDate"), pct(invoice, "discountPct"), pct(invoice, "taxPct"));
        seedLineItems(invoiceId, lineItems);
    }

    /**
     * An invoice's stored amount: an explicit {@code amount} when the fixture gives one (an invoice
     * with no lines), otherwise the sum of its line items' qty * unitPrice.
     */
    private static double invoiceAmount(Map<String, Object> invoice,
            List<Map<String, Object>> lineItems) {
        if (invoice.get("amount") != null) {
            return ((Number) invoice.get("amount")).doubleValue();
        }
        double amount = 0.0;
        if (lineItems != null) {
            for (Map<String, Object> line : lineItems) {
                amount += ((Number) line.get("qty")).doubleValue()
                        * ((Number) line.get("unitPrice")).doubleValue();
            }
        }
        return amount;
    }

    /** Insert an invoice's line items (absent list = none). */
    private void seedLineItems(long invoiceId, List<Map<String, Object>> lineItems) {
        if (lineItems == null) {
            return;
        }
        for (Map<String, Object> line : lineItems) {
            jdbc.update("INSERT INTO invoice_line_items"
                    + " (id, invoice_id, description, qty, unit, unit_price)"
                    + " VALUES (?, ?, ?, ?, ?, ?)",
                    id(line, "id"), invoiceId, line.get("description"),
                    ((Number) line.get("qty")).intValue(),
                    line.getOrDefault("unit", ""),
                    ((Number) line.get("unitPrice")).doubleValue());
        }
    }

    /**
     * Insert every row the fixture supplies under {@code key}, mapping each to the {@code sql}
     * parameters with {@code toParams}. Absent key = nothing to seed. One call per table keeps
     * seeding a new table a single additive line.
     */
    @SuppressWarnings("unchecked")
    private void seedTable(Map<String, Object> fixture, String key, String sql,
            Function<Map<String, Object>, Object[]> toParams) {
        List<Map<String, Object>> rows = (List<Map<String, Object>>) fixture.get(key);
        if (rows == null) {
            return;
        }
        for (Map<String, Object> row : rows) {
            // Explicit fixture id (JPA save() would ignore it — the spec asserts by these ids).
            jdbc.update(sql, toParams.apply(row));
        }
    }

    /**
     * Continue a table's IDENTITY past the highest seeded id, so an API insert after seeding gets a
     * fresh id instead of colliding with a fixture row (H2 does not advance the sequence for the
     * explicit ids a JdbcTemplate seed inserts).
     */
    private void restartIdentity(String table) {
        Long max = jdbc.queryForObject("SELECT COALESCE(MAX(id), 0) FROM " + table, Long.class);
        jdbc.execute("ALTER TABLE " + table + " ALTER COLUMN id RESTART WITH " + (max + 1));
    }

    /** Read a fixture field as a table id (JSON numbers arrive as {@link Number}). */
    private static long id(Map<String, Object> row, String key) {
        return ((Number) row.get(key)).longValue();
    }

    /** Read an optional fixture percentage field (absent = 0). */
    private static double pct(Map<String, Object> row, String key) {
        return row.get(key) == null ? 0.0 : ((Number) row.get(key)).doubleValue();
    }
}
