-- Contacts: the people at a client the owner deals with. Each contact belongs to one client
-- (client_id -> clients.id) and carries a name, an email and their role, so the client's page can
-- list its contacts. (`role` is spelled `contact_role` in the table to dodge any SQL keyword.)
CREATE TABLE contacts (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id    BIGINT NOT NULL REFERENCES clients(id),
    name         VARCHAR(255) NOT NULL,
    email        VARCHAR(255) NOT NULL,
    contact_role VARCHAR(255) NOT NULL
);
