-- Tasks: a project's checklist. Each task has a title, a done flag, and belongs to a project.
-- GENERATED BY DEFAULT (not ALWAYS) so the /__test__ seed path can insert explicit fixture ids.
CREATE TABLE tasks (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(255) NOT NULL,
    done       BOOLEAN      NOT NULL DEFAULT FALSE,
    project_id BIGINT       NOT NULL REFERENCES projects(id)
);
