-- A contact is a person at a client: a name, an email and their role. IDENTITY id so the app
-- generates ids on create, while the test seed inserts explicit ids (GENERATED BY DEFAULT lets a
-- supplied id win). client_id is a FK to clients so a contact always points at a real client.
-- The role column is named contact_role to steer clear of any reserved-word ambiguity.
CREATE TABLE contacts (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    email        VARCHAR(255) NOT NULL,
    contact_role VARCHAR(255) NOT NULL,
    client_id    BIGINT NOT NULL REFERENCES clients (id)
);
