-- Invoice line items: the things an invoice is charging for. Each line has a description, a
-- quantity and a unit price, and belongs to an invoice (invoice_id FK). An invoice's amount is the
-- sum of each line's qty * unit_price. GENERATED BY DEFAULT (not ALWAYS) so the /__test__ seed path
-- can insert explicit fixture ids.
CREATE TABLE invoice_line_items (
    id          BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id  BIGINT        NOT NULL REFERENCES invoices(id),
    description VARCHAR(255)  NOT NULL,
    qty         INTEGER       NOT NULL,
    unit_price  DECIMAL(12,2) NOT NULL
);
