-- Tasks: a checklist item on a project. Each task belongs to one project (project_id -> projects.id)
-- and is either OPEN (done = FALSE, the default) or DONE (done = TRUE), ticked off as work completes.
CREATE TABLE tasks (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id),
    title      VARCHAR(255) NOT NULL,
    done       BOOLEAN NOT NULL DEFAULT FALSE
);
