-- Contacts a user keeps for a client: a name, an email and their role. Each contact belongs to
-- exactly one client (client_id FK). IDENTITY id like client and project, so the DB assigns it on
-- insert while the seed path can still supply explicit ids (GENERATED BY DEFAULT).
CREATE TABLE contact (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES client(id),
    name      VARCHAR(255) NOT NULL,
    email     VARCHAR(255) NOT NULL,
    role      VARCHAR(255) NOT NULL
);
