-- An invoice is now built from line items: one row per thing being charged for — a description, how
-- many (qty), and the price of each (unit_price). An invoice's amount is the sum of qty * unit_price
-- across its lines, so the figure is worked out, never typed. Each line belongs to one invoice
-- (invoice_id -> invoices.id), so an invoice's detail page lists only its own lines.
CREATE TABLE invoice_line_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id  BIGINT NOT NULL REFERENCES invoices(id),
    description VARCHAR(255) NOT NULL,
    qty         INTEGER NOT NULL,
    unit_price  NUMERIC(12, 2) NOT NULL
);
