-- Labels for projects: a reusable pool of tags, and a join table linking a project to each tag it
-- carries so a project can be grouped by any number of labels (many-to-many). GENERATED BY DEFAULT
-- (not ALWAYS) so the /__test__ seed path can insert explicit fixture ids.
CREATE TABLE tags (
    id   BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

-- One row per (project, tag) pairing. The pair is the primary key, so a tag cannot be added to the
-- same project twice.
CREATE TABLE project_tags (
    project_id BIGINT NOT NULL REFERENCES projects(id),
    tag_id     BIGINT NOT NULL REFERENCES tags(id),
    PRIMARY KEY (project_id, tag_id)
);
