-- Notes: free-text notes written on a target (a project for now; target_type/target_id keep it
-- open to other targets later). Each note carries its text and the instant it was written, stored
-- as an ISO-8601 string so the value surfaced is exactly what was stored and newest-first is a
-- simple descending sort. GENERATED BY DEFAULT (not ALWAYS) so the /__test__ seed path can insert
-- explicit fixture ids.
CREATE TABLE notes (
    id          BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type VARCHAR(32)   NOT NULL,
    target_id   BIGINT        NOT NULL,
    note_text   VARCHAR(4000) NOT NULL,
    noted_at    VARCHAR(40)   NOT NULL
);
