-- Fourth domain table: a task is a to-do item that belongs to a project. IDENTITY id so the app
-- generates ids on create, while the test seed inserts explicit ids (GENERATED BY DEFAULT lets a
-- supplied id win). project_id is a FK to projects so a task always points at a real project.
-- done is the tick-off flag: new rows start not-done (the DEFAULT); ticking one flips it to TRUE.
CREATE TABLE tasks (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects (id),
    title      VARCHAR(255) NOT NULL,
    done       BOOLEAN NOT NULL DEFAULT FALSE
);
