-- Tasks a user keeps on a project: a title and a done flag, so a to-do can be ticked off. Each task
-- belongs to exactly one project (project_id FK). IDENTITY id like client, project and contact, so
-- the DB assigns it on insert while the seed path can still supply explicit ids (GENERATED BY
-- DEFAULT). done defaults to FALSE — a freshly added task is OPEN until it is ticked off.
CREATE TABLE task (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project(id),
    title      VARCHAR(255) NOT NULL,
    done       BOOLEAN NOT NULL DEFAULT FALSE
);
