-- Invoices are now itemised: instead of typing one figure, an invoice lists the things being
-- charged for — each line a description, a quantity, and a unit price — and its amount is the sum of
-- quantity * unit price across those lines. This child table holds the lines; each belongs to
-- exactly one invoice (invoice_id FK). IDENTITY id like the other tables, so the DB assigns it on
-- insert while the seed path can still supply explicit ids (GENERATED BY DEFAULT).
CREATE TABLE line_item (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id  BIGINT NOT NULL REFERENCES invoice(id),
    description VARCHAR(255) NOT NULL,
    qty         INTEGER NOT NULL,
    unit_price  NUMERIC(12, 2) NOT NULL
);

-- An itemised invoice with no lines yet totals zero, so the amount can no longer be required to be
-- positive. Drop the check from V8; the amount is now derived from the lines and kept in step by the
-- write paths (the seed and POST /api/lineitems), so the invoice list and dashboard still read it.
ALTER TABLE invoice DROP CONSTRAINT invoice_amount_positive;
