-- An invoice is no longer a single typed-in figure: it is built from LINE ITEMS, each a thing the
-- user is charging for (a description, how many, the price each). The invoice amount is the SUM of
-- every line's quantity times its unit price. This table holds those lines; invoice_id is a FK so a
-- line always belongs to a real invoice. IDENTITY id (GENERATED BY DEFAULT) so the app generates
-- ids on create while the test seed inserts explicit ids.
CREATE TABLE invoice_line_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id  BIGINT NOT NULL REFERENCES invoices (id),
    description VARCHAR(255) NOT NULL,
    quantity    INTEGER NOT NULL CHECK (quantity > 0),
    unit_price  DECIMAL(12, 2) NOT NULL CHECK (unit_price >= 0)
);

-- An invoice's amount is now DERIVED from its line items, so a fresh invoice with no lines yet sums
-- to zero (a DRAFT the user hasn't added anything to). The old "amount must be > 0" guard (V6) no
-- longer holds — drop it. The amount column stays as the maintained sum of the invoice's lines.
ALTER TABLE invoices DROP CONSTRAINT invoices_amount_positive;
