-- Tags and their assignment to projects. A tag is a reusable label (e.g. "urgent", "retainer");
-- project_tags assigns a tag to a project so projects can be grouped by the labels they share. The
-- surrogate id on project_tags keeps the join table a plain IDENTITY row (seeded without an id),
-- while a project is never double-tagged with the same tag (enforced by the app and this unique key).
CREATE TABLE tags (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE project_tags (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id),
    tag_id     BIGINT NOT NULL REFERENCES tags(id),
    UNIQUE (project_id, tag_id)
);
