-- Payments recorded against an invoice: what the client has paid and when. Each payment has an
-- amount and a date, and belongs to an invoice (invoice_id FK). An invoice can have many payments
-- (partial payments over time). The date is stored as an ISO date string (YYYY-MM-DD) so the value
-- the app surfaces is exactly what was stored. GENERATED BY DEFAULT (not ALWAYS) so the /__test__
-- seed path can insert explicit fixture ids.
CREATE TABLE invoice_payments (
    id         BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT        NOT NULL REFERENCES invoices(id),
    amount     DECIMAL(12,2) NOT NULL,
    paid_on    VARCHAR(10)   NOT NULL
);
