-- Fifth domain concept: labels (tags) a user puts on projects to group them. Two tables — the tag
-- catalogue and the many-to-many join to projects.
--
-- tags: a reusable label, IDENTITY id so the app generates ids on create while the test seed inserts
-- explicit ids (GENERATED BY DEFAULT lets a supplied id win).
--
-- project_tags: which tags are on which project. Its primary key is the (project_id, tag_id) pair, so
-- the same label can sit on a project only once; both columns are FKs so a link always points at a
-- real project and a real tag.
CREATE TABLE tags (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE project_tags (
    project_id BIGINT NOT NULL REFERENCES projects (id),
    tag_id     BIGINT NOT NULL REFERENCES tags (id),
    PRIMARY KEY (project_id, tag_id)
);
