-- Labels a user can put on projects to group them: a reusable tag (a name) and a many-to-many join
-- from projects to tags. A tag is created once and can label any number of projects; a project can
-- carry any number of tags. Both tables use IDENTITY ids like client, project, task and contact, so
-- the DB assigns them on insert while the seed path can still supply explicit ids (GENERATED BY
-- DEFAULT). A project_tag row is one (project, tag) pairing; UNIQUE keeps a tag from being applied
-- to the same project twice.
CREATE TABLE tag (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE project_tag (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project(id),
    tag_id     BIGINT NOT NULL REFERENCES tag(id),
    UNIQUE (project_id, tag_id)
);
