-- Notes: a free-text note written against a target (e.g. a project). Each note records what it is
-- about (target_type + target_id), the note text, and when it was written (at). Notes are shown
-- newest first, ordered by `at` descending. `note_text` avoids the reserved word TEXT.
CREATE TABLE notes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type VARCHAR(32) NOT NULL,
    target_id   BIGINT NOT NULL,
    note_text   VARCHAR(2000) NOT NULL,
    at          TIMESTAMP WITH TIME ZONE NOT NULL
);
