-- Free-text notes a user keeps against something (a project, for now). A note is polymorphic: it
-- names its target by (target_type, target_id) rather than a hard FK, so the same table can carry
-- notes for other things later without a schema change. note_text holds the note body; created_at is
-- the ISO-8601 UTC instant it was written, stored as text so it both round-trips exactly and sorts
-- lexically = chronologically (newest first is ORDER BY created_at DESC). IDENTITY id like the other
-- domain tables, so the DB assigns it on insert while the seed path can still supply explicit ids
-- (GENERATED BY DEFAULT allows both).
CREATE TABLE note (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type VARCHAR(32) NOT NULL,
    target_id   BIGINT NOT NULL,
    note_text   VARCHAR(2000) NOT NULL,
    created_at  VARCHAR(64) NOT NULL
);
