-- Fifth domain concept: a note is a free-text remark the user jots against something. It is written
-- generically against a target (target_type + target_id) rather than a single FK, so the same notes
-- surface can later sit on any entity (projects today). IDENTITY id so the app generates ids on
-- create, while the test seed inserts explicit ids (GENERATED BY DEFAULT lets a supplied id win).
-- created_at is when the note was written — the newest-first ordering the UI shows is by this column
-- (DESC), with the id as a stable tie-break. New rows default to now(); the test seed supplies an
-- explicit timestamp so a fixture can pin the order.
CREATE TABLE notes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type VARCHAR(32) NOT NULL,
    target_id   BIGINT NOT NULL,
    text        VARCHAR(4000) NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- The detail page reads one target's notes newest-first, so index the lookup + ordering columns.
CREATE INDEX idx_notes_target ON notes (target_type, target_id, created_at DESC);
