-- A payment recorded against an invoice: what a client has paid, and when. One row per payment —
-- an amount and a date — belonging to one invoice (invoice_id -> invoices.id), so an invoice's
-- detail page lists only its own payments.
CREATE TABLE payments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id  BIGINT NOT NULL REFERENCES invoices(id),
    amount      NUMERIC(12, 2) NOT NULL,
    paid_date   DATE NOT NULL
);
