-- First domain table: a client is a name + email. IDENTITY id so the app can generate ids on
-- create, while the test seed inserts explicit ids (GENERATED BY DEFAULT lets a supplied id win).
CREATE TABLE clients (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL
);
