-- Clients: the first domain table. Name + email per client.
-- GENERATED BY DEFAULT (not ALWAYS) so the /__test__ seed path can insert explicit fixture ids.
CREATE TABLE clients (
    id    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL
);
