-- What a client has PAID against an invoice: each payment is an amount received on a date. An
-- invoice can be paid in parts, so these are rows (not one figure on the invoice). invoice_id is a
-- FK so a payment always belongs to a real invoice. IDENTITY id (GENERATED BY DEFAULT) so the app
-- generates ids on create while the test seed inserts explicit ids. The amount must be positive (a
-- payment is money received), and the date it was paid is required.
CREATE TABLE invoice_payments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id  BIGINT NOT NULL REFERENCES invoices (id),
    amount      DECIMAL(12, 2) NOT NULL CHECK (amount > 0),
    paid_date   DATE NOT NULL
);
