-- A client can pay against an invoice, in one or more instalments. This child table records each
-- payment: how much (amount) and on what day (paid_date). Each payment belongs to exactly one
-- invoice (invoice_id FK). paid_date is stored as text (YYYY-MM-DD) so it round-trips exactly and
-- sorts lexically = chronologically, the same convention the note table uses for its dates.
-- IDENTITY id like the other domain tables, so the DB assigns it on insert while the seed path can
-- still supply explicit ids (GENERATED BY DEFAULT allows both).
CREATE TABLE payment (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id  BIGINT NOT NULL REFERENCES invoice(id),
    amount      NUMERIC(12, 2) NOT NULL,
    paid_date   VARCHAR(32) NOT NULL
);
