-- Second domain table: projects the user does for a client. Each project has a name and belongs to
-- exactly one client (client_id FK). IDENTITY id like client, so the DB assigns it on insert while
-- the seed path can still supply explicit ids (GENERATED BY DEFAULT).
CREATE TABLE project (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(255) NOT NULL,
    client_id BIGINT NOT NULL REFERENCES client(id)
);
