-- Projects: a piece of work the owner does for a client. Each project belongs to one client
-- (client_id -> clients.id), so the projects list can show the client's name via the join.
CREATE TABLE projects (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(255) NOT NULL,
    client_id BIGINT NOT NULL REFERENCES clients(id)
);
