-- Projects: the second domain table. A project has a name and belongs to a client (client_id FK).
-- GENERATED BY DEFAULT (not ALWAYS) so the /__test__ seed path can insert explicit fixture ids.
CREATE TABLE projects (
    id        BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(255) NOT NULL,
    client_id BIGINT       NOT NULL REFERENCES clients(id)
);
