-- Invoices: an amount billed on a project. Each invoice belongs to one project
-- (project_id -> projects.id), so a project's detail page lists ITS invoices and totals them.
CREATE TABLE invoices (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id),
    amount     NUMERIC(12, 2) NOT NULL
);
