-- Invoices: the third domain table. An invoice has a monetary amount and belongs to a project
-- (project_id FK). GENERATED BY DEFAULT (not ALWAYS) so the /__test__ seed path can insert
-- explicit fixture ids.
CREATE TABLE invoices (
    id         BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT        NOT NULL REFERENCES projects(id),
    amount     DECIMAL(12,2) NOT NULL
);
