-- Third domain table: an invoice is an amount that belongs to a project. IDENTITY id so the app
-- generates ids on create, while the test seed inserts explicit ids (GENERATED BY DEFAULT lets a
-- supplied id win). project_id is a FK to projects so an invoice always points at a real project.
-- amount is money, so a fixed-scale DECIMAL (two places) rather than a float.
CREATE TABLE invoices (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects (id),
    amount     DECIMAL(12, 2) NOT NULL
);
