-- Contacts: a client's people. Each contact has a name, an email and a role, and belongs to a client.
-- GENERATED BY DEFAULT (not ALWAYS) so the /__test__ seed path can insert explicit fixture ids.
CREATE TABLE contacts (
    id        BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(255) NOT NULL,
    email     VARCHAR(255) NOT NULL,
    role      VARCHAR(255) NOT NULL,
    client_id BIGINT       NOT NULL REFERENCES clients(id)
);
